---
#Change passwords to actual values when deployed.
version: "4"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
#:amd64-25.01.24
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://10.0.20.13:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/nvme/config/bookstack/bookstackdata:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstackroot
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /mnt/nvme/config/bookstack/bookstackdbdata:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.1
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /host/heimdall/config:/config
    ports:
      - 6876:80
      - 6877:443
    restart: unless-stopped
  heimdall_media_center:
    image: lscr.io/linuxserver/heimdall:2.6.1
    container_name: heimdall_media_center
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/nvme/config/heimdall_media_center/config:/config
    ports:
      - 6878:80
      - 6879:443
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.02.2
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'CHANGEME'
    volumes:
      - '/mnt/nvme/config/pihole/etc-pihole:/etc/pihole'
      - '/mnt/nvme/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:amd64-8.0.28-ls31
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_mongo_pass123
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - /mnt/nvme/config/unifi_network_application:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
  unifi-db:
    image: docker.io/mongo:jammy
    container_name: unifi-db
    ports:
    - 27017:27103
    volumes:
      - /mnt/nvme/config/mongo/data:/data/db
      - /mnt/nvme/config/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

