---
#Change passwords to actual values when deployed.
version: "4"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
#:amd64-25.01.24
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://10.0.20.13:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/nvme/config/bookstack/bookstackdata:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstackroot
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /mnt/nvme/config/bookstack/bookstackdbdata:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.1
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /host/heimdall/config:/config
    ports:
      - 6876:80
      - 6877:443
    restart: unless-stopped
  heimdall_media_center:
    image: lscr.io/linuxserver/heimdall:2.6.1
    container_name: heimdall_media_center
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/nvme/config/heimdall_media_center/config:/config
    ports:
      - 6878:80
      - 6879:443
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.02.2
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'CHANGEME'
    volumes:
      - '/mnt/nvme/config/pihole/etc-pihole:/etc/pihole'
      - '/mnt/nvme/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:2.11.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/nvme/config/nginx_proxy_manager/data:/data
      - /mnt/nvme/config/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.0
    restart: unless-stopped
    volumes:
      - /mnt/nvme/config/homarr/configs:/app/data/configs
      - /mnt/nvme/config/homarr/icons:/app/public/icons
      - /mnt/nvme/config/homarr/data:/data
    ports:
      - '7575:7575'
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /mnt/nvme/config/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  gitea:
    image: gitea/gitea:1.21.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=giteadb:3307
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - /mnt/nvme/config/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - giteadb
  giteadb:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_TCP_PORT=3307
    volumes:
      - /mnt/nvme/config/giteadb:/var/lib/mysql
  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvme/config/wekan/wekan-db:/data/db
      - /mnt/nvme/config/wekan/wekan-db-dump:/dump
  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan
    restart: always
    ports:
      - 3003:8080
    environment:
      - USER_GID=1000
      - USER_UID=1000
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://wekan.home.local
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvme/config/wekan/wekan-files:/data
